(define mylist '(12 71 2 15 29 82 87 8 18 66 81 25 63 97 40 3 93 58 53 31 47))
(define (filter-less-equal pivot lst)
(if (null? lst) '() (if (<= (car lst) pivot) (cons (car lst) (filter-less-equal pivot (cdr lst))) (filter-less-equal pivot (cdr lst)))))
(define (filter-greater pivot lst)
(if (null? lst) '() (if (> (car lst) pivot) (cons (car lst) (filter-greater pivot (cdr lst))) (filter-greater pivot (cdr lst)))))
(define (quicksort lst)
(if (null? lst) '() (if (null? (cdr lst)) lst (let ((pivot (car lst)) (rest (cdr lst))) (let ((less-equal-partition (filter-less-equal pivot rest)) (greater-partition (filter-greater pivot rest))) (append (quicksort less-equal-partition) (cons pivot (quicksort greater-partition))))))))
(print (quicksort '(12 71 2 15 29 82 87 8 18 66 81 25 63 97 40 3 93 58 53 31 47)))
(exit 0) 